# Generated by Django 4.2.3 on 2025-02-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdCourse',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IdQuastion',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Quastion', models.CharField(max_length=60)),
                ('Option_a', models.CharField(max_length=50)),
                ('Option_b', models.CharField(max_length=50)),
                ('Option_c', models.CharField(max_length=50)),
                ('Option_d', models.CharField(max_length=50)),
                ('Correct_Option', models.CharField(max_length=1)),
                ('IdCoursef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.idcourse')),
            ],
        ),
    ]
