# Generated by Django 4.2.3 on 2025-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idquastion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
